"""Pydantic models for the ParsedBill contract (aligned to Vitta)."""

from app.models.parsed_bill import (
    AppealPrediction,
    AppealSuccess,
    CodeValidation,
    DocumentMetadata,
    DocumentStatus,
    DocumentType,
    ExtractionWarning,
    FieldConfidence,
    Flag,
    Letter,
    LineItem,
    ParsedBill,
    PlaceOfService,
    PricingAnomaly,
    Provenance,
    ShapExplanation,
    Totals,
    VerificationStatus,
    WarningSeverity,
)

__all__ = [
    "AppealPrediction",
    "AppealSuccess",
    "CodeValidation",
    "DocumentMetadata",
    "DocumentStatus",
    "DocumentType",
    "ExtractionWarning",
    "FieldConfidence",
    "Flag",
    "Letter",
    "LineItem",
    "ParsedBill",
    "PlaceOfService",
    "PricingAnomaly",
    "Provenance",
    "ShapExplanation",
    "Totals",
    "VerificationStatus",
    "WarningSeverity",
]